apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  
  serviceMonitorSelector: 
    matchLabels:
      name: prometheus
  resources:
    requests:
      memory: 400Mi

