apiVersion: v1
kind: Service
metadata:
  name: applicationservice
  labels:
    name: applicationservice
    
spec:
  selector:
    app: monitoring-prometheus
  ports:
  - port: 5000
    targetPort: 1234
    name: port
